name: shop_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  conditional_builder_null_safety: ^0.0.6
  hexcolor: ^3.0.1
  shared_preferences: ^2.1.0
  smooth_page_indicator: ^1.1.0
  dio: ^5.1.1
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
     - family: Jannah
       fonts:
         - asset: assets/fonts/jannah_font.ttf

